@startuml

abstract class Robot358Main
abstract class AutoEngine358
abstract class AutoEngine358
abstract class RobotAction
interface StopperIF
interface TurnerIF
class TeleOp358
class ScoreAction
class RobotPosition
class



@enduml